# Generated by Django 3.2 on 2022-04-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R000', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studant',
            name='accept_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='accept_degeer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='accept_type',
            field=models.CharField(choices=[('ganral', 'ganral'), ('privet', 'privet')], max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='born_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='born_in',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='email',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='gender',
            field=models.CharField(choices=[('meal', 'meal'), ('femeal', 'femeal')], max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='public_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='school_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='toll',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='universitiy_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
