# Generated by Django 3.2 on 2022-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('R000', '0003_auto_20220417_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studant',
            name='gender',
            field=models.CharField(choices=[('زكر', 'زكر'), ('انثى', 'انثى')], max_length=190, null=True),
        ),
    ]
