# Generated by Django 3.2 on 2022-04-17 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('R000', '0005_alter_studant_accept_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studant',
            name='certificate_type',
            field=models.CharField(choices=[('اكاديمي', 'أكاديمي'), ('فني', 'فني'), ('تجاري', 'تجاري')], max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='religion',
            field=models.CharField(choices=[('مسلم', 'مسلم'), ('مسيحي', 'مسيحي'), ('غير', 'غير')], max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='studant',
            name='accept_type',
            field=models.CharField(choices=[('قبول عام', 'قبول عم'), ('قبول خاص', 'قبول خاص')], max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='studant',
            name='toll_status',
            field=models.CharField(choices=[('تم التسديد', 'تم التسديد '), ('لم يتم التسديد', 'لم يتم التسديد')], max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='studant',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studant_nationality', to='R000.nationality'),
        ),
    ]
