# Generated by Django 4.0.1 on 2022-11-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('R000', '0007_studant_blood_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semster_program', to='R000.program')),
            ],
        ),
        migrations.RemoveField(
            model_name='studant',
            name='batch',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.AddField(
            model_name='studant',
            name='semster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studant_semster', to='R000.semster'),
        ),
    ]
