# Generated by Django 4.0.1 on 2022-11-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('R000', '0009_batch_remove_semster_program_delete_program_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semster',
            old_name='Batch',
            new_name='batch',
        ),
    ]
